//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deduc()
        {
            this.Payroll = new HashSet<Payroll>();
        }
    
        public int DeductionID { get; set; }
        public int EmployeeID { get; set; }
        public int TaxAmount { get; set; }
        public int AlimonyAmount { get; set; }
        public int OtherDeductions { get; set; }
        public int TotalDeductions { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payroll> Payroll { get; set; }
    }
}
